### ISSUE TITLE
The app_timer usage may conflict

### ISSUE THREAD

**Issue by xiongyihui** [mbedmicro/nRF51822#2]
In the mbed SDK, [us_ticker.c](https://github.com/ohagendorf/mbed/blob/master/libraries/mbed/targets/hal/TARGET_NORDIC/TARGET_MCU_NRF51822/us_ticker.c#L32) initializes  app_timer with one available instance which is only for itself, but [ble_conn_params.cpp](https://github.com/mbedmicro/nRF51822/blob/master/nordic/ble/ble_conn_params.cpp#L123) also try to use app_timer.

Perhaps, we should use the API of us_ticker_api.h in ble_conn_params.cpp

**Comment by rgrover** [comment]
Yes, this is a problem which needs looking into. thanks for bringing this up.

**Comment by rgrover** [comment]
addressed with commit 2c5d9aecb8ccaa51aa6560ee83b8aafe185b8227
